### ISSUE TITLE
asgard-unit-gxx-mkl fails time_advance-test

### ISSUE THREAD

**Issue by quantumsteve** [project-asgard/asgard#591] opened 2023-07-19 21:12 UTC
**Describe the bug**

```
18/26 Test #18: time_advance-test ................***Failed  1231.28 sec
--
361 | Randomness seeded to: 1253051028
362 |  
363 | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
364 | time_advance-tests is a Catch2 v3.1.0 host application.
365 | Run with -? for options
366 |  
367 | -------------------------------------------------------------------------------
368 | IMEX time advance - landau - float
369 | -------------------------------------------------------------------------------
370 | /codebuild/output/src1485245485/src/github.com/project-asgard/asgard/src/time_advance_tests.cpp:1238
371 | ...............................................................................
372 |  
373 | /codebuild/output/src1485245485/src/github.com/project-asgard/asgard/src/time_advance_tests.cpp:1333: FAILED:
374 | REQUIRE( E_relative <= tolerance )
375 | with expansion:
376 | nanf <= 0.00000999999974737875f

```

**To Reproduce**

See asgard-unit-gxx-mkl on AWS Codebuild

**Expected behavior**

**System:**
 - system name [e.g. fusiont5, summit] AWS Codebuild
 - modules loaded [e.g. output of `module list`]  https://github.com/project-asgard/containers/blob/main/cpu_mkl/Dockerfile
 - other systems where this is reproducible [e.g. "my laptop", "none"]

**Additional context**

I haven't successfully reproduced this on my two Intel machines or with the Docker image we pushed to AWS.

**Comment by quantumsteve** [comment] 2023-07-19 21:13
#590 skips the failing test

**Comment by quantumsteve** [comment] 2023-07-19 21:15
@ckendrick Would you try reproducing this?

**Comment by ckendrick** [comment] 2023-07-19 21:53
I'll take a look at this. It seems strange this is failing only for float and not double (unless float was run first).

**Comment by mkstoyanov** [comment] 2023-07-19 21:58
I think float runs first in all tests that use both precisions.

**Comment by ckendrick** [comment] 2023-07-19 22:03
Ah so it is likely the `double` case never runs then. I'm trying this on `andremarie` right now which is using MKL.

**Comment by ckendrick** [comment] 2023-07-19 22:22
@quantumsteve I can't reproduce this either using the MKL setup on `andremarie`. Both `float` and `double` tests pass.

**Comment by quantumsteve** [comment] 2023-07-19 22:44
I removed `MKL_ENABLE_INSTRUCTIONS=AVX2` from our CI build. Shouldn't make a different but we'll see.

**Comment by mkstoyanov** [comment] 2024-06-27 14:22
AVX and FMA instruction can lead to different rounding error and some of the test tolerances are unreasonably tight. We can revisit this on a case-by-case basis but we can close the issue.

**Closed as completed by mkstoyanov** 2024-06-27 14:22 UTC
