### ISSUE TITLE
apply_fmwt function tests sporadically failing

### ISSUE THREAD

**Issue by tyounkin** [project-asgard/asgard#132] opened 2019-08-02 18:52 UTC
There is an intermittent failure in apply_fmwt() here. To reproduce:

cmake -DCMAKE_CXX_COMPILER=clang++
make -j
for bob in $(seq 1 20) ; do ./basis-tests ; done

In the testing of this routine, random input is generated and then tested. With the test usually passing, but close to the tolerable error, the test occasionally fails.

The testing needs to be updated to use Catch::Matchers::WithinAbs and use matrix size and values to be more accurate.

**Comment by grahamlopez** [comment] 2019-08-21 17:59
I cannot reproduce this anymore, with either clang or gcc. It looks like David updated the relaxed compare lambda with `Catch::Matchers::WithinAbs` in e9aa6af47 (merged as part of #118).

**Closed** 2019-08-22 15:06 UTC
